# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseUrl = http://localhost:8080

###
GET {{baseUrl}}/health

###
GET {{baseUrl}}/products

###
GET {{baseUrl}}/external-data

###
GET {{baseUrl}}/reports