@baseUrl = http://localhost:5220
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YjI2NjMyOC0yOWI0LTQwYWQtYmFmMi0zN2MxNDNiMDY5NmMiLCJlbWFpbCI6ImFsaWNlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjU4MzgzMywiaXNzIjoid2F0Y2h0b3dlci1hcGkiLCJhdWQiOiJ3YXRjaHRvd2VyLWNsaWVudHMifQ.PL2tgExpt5T9GtrgQkVBhqqCiY1hH1DnIjLobgSx0dw
@endpointId = 94139e58-0c4e-4da6-bff9-253ff37e54ed

### 1. Get All Endpoints
GET {{baseUrl}}/endpoints
Authorization: Bearer {{token}}

### 2. Get Endpoint By Id
GET {{baseUrl}}/endpoints/{{endpointId}}
Authorization: Bearer {{token}}

### 3. Create Endpoint
POST {{baseUrl}}/endpoints
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "FakeTarget Health",
  "url": "http://localhost:8080/health",
  "httpMethod": "GET",
  "checkIntervalSeconds": 60,
  "timeoutSeconds": 10,
  "expectedStatusCode": 200,
  "expectedBodyContains": null,
  "maxResponseTimeMs": 3000
}

### 4. Update Endpoint
PUT {{baseUrl}}/endpoints/{{endpointId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "FakeTarget Health (updated)",
  "url": "http://localhost:8080/health",
  "httpMethod": "GET",
  "checkIntervalSeconds": 120,
  "timeoutSeconds": 15,
  "expectedStatusCode": 200,
  "expectedBodyContains": null,
  "maxResponseTimeMs": 5000
}

### 5. Toggle Endpoint (pause / resume)
PATCH {{baseUrl}}/endpoints/{{endpointId}}/toggle
Authorization: Bearer {{token}}

### 6. Delete Endpoint
DELETE {{baseUrl}}/endpoints/{{endpointId}}
Authorization: Bearer {{token}}
